--@ module=true

local CATEGORY_LABOR = 'Labor'
local CATEGORY_COMBAT = 'Combat'
local CATEGORY_SOCIAL = 'Social'
local CATEGORY_OTHER = 'Other Skills'
local CATEGORY_KNOWLEDGE = 'Knowledge'

-- Category order is presentation metadata shared by the descriptor catalog and
-- picker UI. Treat this table and the mapping below as immutable.
local CATEGORY_ORDER = {
    CATEGORY_LABOR,
    CATEGORY_COMBAT,
    CATEGORY_SOCIAL,
    CATEGORY_OTHER,
    CATEGORY_KNOWLEDGE,
}

local CATEGORY_BY_KEY = {
    MINING=CATEGORY_LABOR,
    WOODCUTTING=CATEGORY_LABOR,
    WOOD_CUTTING=CATEGORY_LABOR,
    CARPENTRY=CATEGORY_LABOR,
    BOWYER=CATEGORY_LABOR,
    DETAILSTONE=CATEGORY_LABOR,
    ENGRAVING=CATEGORY_LABOR,
    STONECUTTING=CATEGORY_LABOR,
    STONE_CUTTING=CATEGORY_LABOR,
    STONE_CARVING=CATEGORY_LABOR,
    MASONRY=CATEGORY_LABOR,
    ANIMALTRAIN=CATEGORY_LABOR,
    ANIMAL_TRAINING=CATEGORY_LABOR,
    ANIMALCARE=CATEGORY_LABOR,
    ANIMAL_CARE=CATEGORY_LABOR,
    DISSECT_FISH=CATEGORY_LABOR,
    DISSECT_VERMIN=CATEGORY_LABOR,
    PROCESSFISH=CATEGORY_LABOR,
    FISH_CLEANING=CATEGORY_LABOR,
    FISHING=CATEGORY_LABOR,
    BUTCHER=CATEGORY_LABOR,
    TRAPPING=CATEGORY_LABOR,
    TANNER=CATEGORY_LABOR,
    BREWING=CATEGORY_LABOR,
    CHEESEMAKING=CATEGORY_LABOR,
    CHEESE_MAKING=CATEGORY_LABOR,
    MILK=CATEGORY_LABOR,
    MILKING=CATEGORY_LABOR,
    GELD=CATEGORY_LABOR,
    GELDING=CATEGORY_LABOR,
    PLANT=CATEGORY_LABOR,
    PLANTING=CATEGORY_LABOR,
    HERBALISM=CATEGORY_LABOR,
    SOAP_MAKING=CATEGORY_LABOR,
    POTASH_MAKING=CATEGORY_LABOR,
    LYE_MAKING=CATEGORY_LABOR,
    DYEING=CATEGORY_LABOR,
    COOK=CATEGORY_LABOR,
    COOKING=CATEGORY_LABOR,
    MILLING=CATEGORY_LABOR,
    PROCESS_PLANTS=CATEGORY_LABOR,
    SHEARING=CATEGORY_LABOR,
    SPINNING=CATEGORY_LABOR,
    PRESSING=CATEGORY_LABOR,
    BEEKEEPING=CATEGORY_LABOR,
    WAX_WORKING=CATEGORY_LABOR,
    WOOD_BURNING=CATEGORY_LABOR,
    FURNACE_OPERATING=CATEGORY_LABOR,
    WEAPONSMITH=CATEGORY_LABOR,
    WEAPONSMITHING=CATEGORY_LABOR,
    ARMORER=CATEGORY_LABOR,
    ARMORSMITH=CATEGORY_LABOR,
    ARMORSMITHING=CATEGORY_LABOR,
    BLACKSMITH=CATEGORY_LABOR,
    BLACKSMITHING=CATEGORY_LABOR,
    METALCRAFT=CATEGORY_LABOR,
    METALCRAFTING=CATEGORY_LABOR,
    GEM_CUTTING=CATEGORY_LABOR,
    GEM_SETTING=CATEGORY_LABOR,
    WOODCRAFT=CATEGORY_LABOR,
    WOOD_CRAFTING=CATEGORY_LABOR,
    STONECRAFT=CATEGORY_LABOR,
    STONE_CRAFTING=CATEGORY_LABOR,
    BONECARVE=CATEGORY_LABOR,
    BONE_CARVING=CATEGORY_LABOR,
    GLASSMAKER=CATEGORY_LABOR,
    GLASSMAKING=CATEGORY_LABOR,
    GLAZING=CATEGORY_LABOR,
    WEAVING=CATEGORY_LABOR,
    CLOTHESMAKING=CATEGORY_LABOR,
    CLOTHIER=CATEGORY_LABOR,
    LEATHERWORK=CATEGORY_LABOR,
    LEATHERWORKING=CATEGORY_LABOR,
    STRAND_EXTRACTION=CATEGORY_LABOR,
    POTTERY=CATEGORY_LABOR,
    PAPERMAKING=CATEGORY_LABOR,
    PAPER_MAKING=CATEGORY_LABOR,
    BOOKBINDING=CATEGORY_LABOR,
    BOOK_BINDING=CATEGORY_LABOR,
    MECHANICS=CATEGORY_LABOR,
    SIEGECRAFT=CATEGORY_LABOR,
    SIEGE_ENGINEERING=CATEGORY_LABOR,
    SIEGEOPERATE=CATEGORY_LABOR,
    SIEGE_OPERATING=CATEGORY_LABOR,
    PUMP_OPERATE=CATEGORY_LABOR,
    PUMP_OPERATING=CATEGORY_LABOR,
    KNAPPING=CATEGORY_LABOR,

    ARCHERY=CATEGORY_COMBAT,
    ARCHER=CATEGORY_COMBAT,
    ARMOR=CATEGORY_COMBAT,
    ARMOR_USER=CATEGORY_COMBAT,
    AXE=CATEGORY_COMBAT,
    AXEMAN=CATEGORY_COMBAT,
    BITE=CATEGORY_COMBAT,
    BITER=CATEGORY_COMBAT,
    BLOWGUN=CATEGORY_COMBAT,
    BLOWGUNNER=CATEGORY_COMBAT,
    BOW=CATEGORY_COMBAT,
    BOWMAN=CATEGORY_COMBAT,
    CROSSBOW=CATEGORY_COMBAT,
    CROSSBOWMAN=CATEGORY_COMBAT,
    DODGE=CATEGORY_COMBAT,
    DODGER=CATEGORY_COMBAT,
    FIGHTING=CATEGORY_COMBAT,
    FIGHTER=CATEGORY_COMBAT,
    HAMMER=CATEGORY_COMBAT,
    HAMMERMAN=CATEGORY_COMBAT,
    KICK=CATEGORY_COMBAT,
    KICKER=CATEGORY_COMBAT,
    KNIFE=CATEGORY_COMBAT,
    KNIFE_USER=CATEGORY_COMBAT,
    LASH=CATEGORY_COMBAT,
    LASHER=CATEGORY_COMBAT,
    MACE=CATEGORY_COMBAT,
    MACEMAN=CATEGORY_COMBAT,
    MILITARY_TACTICS=CATEGORY_COMBAT,
    MISC_OBJECT=CATEGORY_COMBAT,
    MISC_OBJECT_USER=CATEGORY_COMBAT,
    MISC_WEAPON=CATEGORY_COMBAT,
    PIKE=CATEGORY_COMBAT,
    PIKEMAN=CATEGORY_COMBAT,
    SHIELD=CATEGORY_COMBAT,
    SHIELD_USER=CATEGORY_COMBAT,
    SPEAR=CATEGORY_COMBAT,
    SPEARMAN=CATEGORY_COMBAT,
    STRIKE=CATEGORY_COMBAT,
    STRIKER=CATEGORY_COMBAT,
    SWORD=CATEGORY_COMBAT,
    SWORDSMAN=CATEGORY_COMBAT,
    THROW=CATEGORY_COMBAT,
    THROWER=CATEGORY_COMBAT,
    WRESTLE=CATEGORY_COMBAT,
    WRESTLER=CATEGORY_COMBAT,
    DISCIPLINE=CATEGORY_COMBAT,

    APPRAISAL=CATEGORY_SOCIAL,
    ORGANIZATION=CATEGORY_SOCIAL,
    RECORD_KEEPING=CATEGORY_SOCIAL,
    COMEDY=CATEGORY_SOCIAL,
    CONVERSATION=CATEGORY_SOCIAL,
    FLATTERY=CATEGORY_SOCIAL,
    INTIMIDATION=CATEGORY_SOCIAL,
    JUDGING_INTENT=CATEGORY_SOCIAL,
    LYING=CATEGORY_SOCIAL,
    NEGOTIATION=CATEGORY_SOCIAL,
    PERSUASION=CATEGORY_SOCIAL,
    LEADERSHIP=CATEGORY_SOCIAL,
    TEACHING=CATEGORY_SOCIAL,
    CONSOLE=CATEGORY_SOCIAL,
    CONSOLING=CATEGORY_SOCIAL,
    PACIFY=CATEGORY_SOCIAL,
    PACIFICATION=CATEGORY_SOCIAL,
    SCHEMING=CATEGORY_SOCIAL,

    CRITICAL_THINKING=CATEGORY_KNOWLEDGE,
    LOGIC=CATEGORY_KNOWLEDGE,
    MATHEMATICS=CATEGORY_KNOWLEDGE,
    ASTRONOMY=CATEGORY_KNOWLEDGE,
    CHEMISTRY=CATEGORY_KNOWLEDGE,
    GEOGRAPHY=CATEGORY_KNOWLEDGE,
    OPTICS_ENGINEER=CATEGORY_KNOWLEDGE,
    OPTICS_ENGINEERING=CATEGORY_KNOWLEDGE,
    FLUID_ENGINEER=CATEGORY_KNOWLEDGE,
    FLUID_ENGINEERING=CATEGORY_KNOWLEDGE,
    WORDSMITH=CATEGORY_KNOWLEDGE,
    WRITING=CATEGORY_KNOWLEDGE,

    CLIMBING=CATEGORY_OTHER,
    CONCENTRATION=CATEGORY_OTHER,
    CRUTCH_WALK=CATEGORY_OTHER,
    CRUTCH_WALKING=CATEGORY_OTHER,
    OBSERVER=CATEGORY_OTHER,
    READING=CATEGORY_OTHER,
    RIDING=CATEGORY_OTHER,
    STUDENT=CATEGORY_OTHER,
    SWIMMING=CATEGORY_OTHER,
    TRACKING=CATEGORY_OTHER,
    DANCING=CATEGORY_OTHER,
    SINGING=CATEGORY_OTHER,
    MUSICIAN=CATEGORY_OTHER,
    POET=CATEGORY_OTHER,
    SPEAKER=CATEGORY_OTHER,
    KEYBOARD_INSTRUMENT=CATEGORY_OTHER,
    STRINGED_INSTRUMENT=CATEGORY_OTHER,
    WIND_INSTRUMENT=CATEGORY_OTHER,
    PERCUSSION_INSTRUMENT=CATEGORY_OTHER,
    BALANCE=CATEGORY_OTHER,
    COORDINATION=CATEGORY_OTHER,
    DRUID=CATEGORY_OTHER,
}

---Returns the presentation category for a skill key.
---@param skill_key string
---@return string
function get_category(skill_key)
    return CATEGORY_BY_KEY[skill_key] or CATEGORY_OTHER
end

---Returns the immutable category presentation order.
---@return string[]
function get_order()
    return CATEGORY_ORDER
end

---Checks whether a skill has an explicit taxonomy entry.
---@param skill_key string
---@return boolean
function is_known(skill_key)
    return CATEGORY_BY_KEY[skill_key] ~= nil
end

---Returns explicit taxonomy keys in stable alphabetical order.
---@return string[]
function get_known_keys()
    local keys = {}
    for key in pairs(CATEGORY_BY_KEY) do
        table.insert(keys, key)
    end
    table.sort(keys)
    return keys
end

---Finds keys that use the forward-compatible fallback category.
---This supports tests and explicit development inspection; it never prints
---during normal use.
---@param skill_keys string[]
---@return string[]
function get_uncategorized(skill_keys)
    local result = {}
    for _, key in ipairs(skill_keys) do
        if not is_known(key) then
            table.insert(result, key)
        end
    end
    table.sort(result)
    return result
end
