local soulsearch_env = require('support.soulsearch_env')

local function screen(l, t, w, h)
    return {window={frame={l=l, t=t, w=w, h=h}}}
end

return function(test, repo_root)
    local registry = soulsearch_env.load_screen_registry(repo_root)

    test.case('screen registry: add is unique and snapshots are isolated', function()
        registry.clear()
        local first, second = screen(1, 2, 20, 10), screen(3, 4, 20, 10)
        test.assert_true(registry.add(first))
        test.assert_false(registry.add(first))
        test.assert_true(registry.add(second))
        test.assert_equal(2, registry.count())
        test.assert_true(registry.contains(first))
        local snapshot = registry.snapshot()
        table.remove(snapshot, 1)
        test.assert_equal(2, registry.count())
        local frames = registry.get_frames()
        frames[1].l = 99
        test.assert_equal(1, first.window.frame.l)
    end)

    test.case('screen registry: removal is idempotent and order independent', function()
        registry.clear()
        local first = screen(1, 1, 20, 10)
        local second = screen(2, 2, 20, 10)
        local third = screen(3, 3, 20, 10)
        registry.add(first)
        registry.add(second)
        registry.add(third)
        test.assert_true(registry.remove(second))
        test.assert_false(registry.remove(second))
        test.assert_equal(2, registry.count())
        test.assert_true(registry.contains(first))
        test.assert_true(registry.contains(third))
        test.assert_true(registry.remove(first))
        test.assert_true(registry.remove(third))
        test.assert_equal(0, registry.count())
    end)

    test.case('screen registry: snapshot iteration tolerates registry mutation', function()
        registry.clear()
        local first = screen(1, 1, 20, 10)
        local second = screen(2, 2, 20, 10)
        local third = screen(3, 3, 20, 10)
        local added_during_iteration = screen(4, 4, 20, 10)
        registry.add(first)
        registry.add(second)
        registry.add(third)

        local visited = {}
        registry.for_each_snapshot(function(active)
            table.insert(visited, active)
            registry.remove(active)
            if active == first then
                registry.remove(third)
                registry.add(added_during_iteration)
            end
        end)

        test.assert_equal(3, #visited)
        test.assert_true(visited[1] == first)
        test.assert_true(visited[2] == second)
        test.assert_true(visited[3] == third)
        test.assert_equal(1, registry.count())
        test.assert_true(registry.contains(added_during_iteration))
    end)

    test.case('screen registry: overlapping frames cascade diagonally', function()
        registry.clear()
        local base = {l=10, t=10, w=60, h=30}
        local first = registry.place_frame(base, 100, 50)
        test.assert_equal(10, first.l)
        test.assert_equal(10, first.t)
        registry.add(screen(first.l, first.t, first.w, first.h))
        local second = registry.place_frame(base, 100, 50)
        test.assert_equal(12, second.l)
        test.assert_equal(12, second.t)
        registry.add(screen(second.l, second.t, second.w, second.h))
        local third = registry.place_frame(base, 100, 50)
        test.assert_equal(14, third.l)
        test.assert_equal(14, third.t)
        test.assert_equal(10, base.l)
        test.assert_equal(10, base.t)
    end)

    test.case('screen registry: cascade wraps within screen bounds', function()
        registry.clear()
        registry.add(screen(40, 20, 60, 30))
        local placed = registry.place_frame(
            {l=40, t=20, w=60, h=30}, 100, 50)
        test.assert_equal(1, placed.l)
        test.assert_equal(1, placed.t)
        test.assert_true(placed.l + placed.w <= 100)
        test.assert_true(placed.t + placed.h <= 50)
    end)
end
