local soulsearch_env = require('support.soulsearch_env')

return function(test, repo_root)
    test.case('stats layout: component geometry and hitboxes are stable', function()
        local layout = soulsearch_env.load_stats_layout(repo_root)
        test.assert_equal('label', layout.get_header_column(0, 0))
        test.assert_equal('label', layout.get_header_column(22, 0))
        test.assert_equal('value', layout.get_header_column(26, 0))
        test.assert_nil(layout.get_header_column(23, 0))
        test.assert_nil(layout.get_header_column(26, 1))
        test.assert_true(layout.is_label_cell(2, 0))
        test.assert_true(layout.is_value_cell(32, 0))
        local compact = layout.get_overlay_columns(false)
        test.assert_equal(27, compact.value_column_x)
        test.assert_equal(24, compact.label_width)
        local scrolling = layout.get_overlay_columns(true)
        test.assert_equal(25, scrolling.value_column_x)
        test.assert_equal(22, scrolling.label_width)
        test.assert_true(layout.is_value_cell(25, 0, scrolling))
        test.assert_false(layout.is_value_cell(25, 0, compact))
        local frames = layout.get_content_frames(12, 10, 3)
        test.assert_equal(0, frames.header.t)
        test.assert_equal(9, frames.header.h)
        test.assert_equal(9, frames.columns.t)
        test.assert_equal(2, frames.columns.h)
        test.assert_equal(11, frames.body.t)
        local minimum = layout.get_content_frames(1, 1, 2)
        test.assert_equal(2, minimum.body.t)
    end)
end
