local soulsearch_env = require('support.soulsearch_env')

local repo_root = require('support.repo_root')

describe('stats layout', function()

    it('stats layout: component geometry and hitboxes are stable', function()
        local layout = soulsearch_env.load_stats_layout(repo_root)
        assert.are.equal('label', layout.get_header_column(0, 0))
        assert.are.equal('label', layout.get_header_column(22, 0))
        assert.are.equal('value', layout.get_header_column(26, 0))
        assert.is_nil(layout.get_header_column(23, 0))
        assert.is_nil(layout.get_header_column(26, 1))
        assert.is_truthy(layout.is_label_cell(2, 0))
        assert.is_truthy(layout.is_value_cell(32, 0))
        local compact = layout.get_overlay_columns(false)
        assert.are.equal(27, compact.value_column_x)
        assert.are.equal(26, compact.label_width)
        assert.are.equal(0, compact.label_inset)
        local scrolling = layout.get_overlay_columns(true)
        assert.are.equal(25, scrolling.value_column_x)
        assert.are.equal(24, scrolling.label_width)
        assert.are.equal(0, scrolling.label_inset)
        assert.is_truthy(layout.is_label_cell(0, 0, compact))
        assert.is_truthy(layout.is_value_cell(25, 0, scrolling))
        assert.is_falsy(layout.is_value_cell(25, 0, compact))
        local frames = layout.get_content_frames(12, 10, 3)
        assert.are.equal(0, frames.header.t)
        assert.are.equal(9, frames.header.h)
        assert.are.equal(9, frames.columns.t)
        assert.are.equal(2, frames.columns.h)
        assert.are.equal(11, frames.body.t)
        local minimum = layout.get_content_frames(1, 1, 2)
        assert.are.equal(2, minimum.body.t)
    end)

end)