local soulsearch_env = require('support.soulsearch_env')

return function(test, repo_root)
    test.case('stats layout: component geometry and hitboxes are stable', function()
        local layout = soulsearch_env.load_stats_layout(repo_root)
        test.assert_equal('label', layout.get_header_column(0, 0))
        test.assert_equal('label', layout.get_header_column(23, 0))
        test.assert_equal('value', layout.get_header_column(27, 0))
        test.assert_nil(layout.get_header_column(24, 0))
        test.assert_nil(layout.get_header_column(27, 1))
        test.assert_true(layout.is_label_cell(2, 0))
        test.assert_true(layout.is_value_cell(33, 0))
        local frames = layout.get_content_frames(12, 10, 3)
        test.assert_equal(2, frames.header.t)
        test.assert_equal(7, frames.header.h)
        test.assert_equal(9, frames.columns.t)
        test.assert_equal(2, frames.columns.h)
        test.assert_equal(11, frames.body.t)
        local minimum = layout.get_content_frames(1, 1, 2)
        test.assert_equal(4, minimum.body.t)
    end)
end
